# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('PhoneNo', models.CharField(max_length=50, unique=True)),
                ('EmailId', models.EmailField(blank=True, max_length=254)),
                ('AvgRating', models.FloatField(blank=True, default=3.0, null=True)),
                ('n', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
