# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0002_auto_20170607_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNo',
            field=models.CharField(max_length=20),
        ),
    ]
