# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0003_auto_20170607_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='PhoneNo',
        ),
    ]
