# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0004_remove_user_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PhoneNo',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
