# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0005_user_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='AvgRating',
            field=models.FloatField(blank=True, default=3.0),
        ),
    ]
