# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0010_auto_20170613_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AccessToken',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
