# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('PhoneNo', models.CharField(max_length=50, unique=True)),
                ('EmailId', models.EmailField(blank=True, max_length=254)),
                ('City', models.CharField(blank=True, default=b'Delhi', max_length=200, null=True)),
                ('IdNumber', models.CharField(blank=True, max_length=50)),
                ('IdType', models.CharField(choices=[(b'Aadhar Card', b'Aadhar Card'), (b'Voter Id Card', b'Voter Id Card')], default=b'Aadhar Card', max_length=100)),
                ('Vehicle', models.CharField(blank=True, default=b'Car', max_length=50)),
                ('AvgRating', models.FloatField(blank=True, default=3.0, null=True)),
                ('n', models.IntegerField(blank=True, default=0)),
                ('A', models.IntegerField(blank=True, default=0)),
                ('B', models.IntegerField(blank=True, default=0)),
                ('C', models.IntegerField(blank=True, default=0)),
                ('D', models.IntegerField(blank=True, default=0)),
                ('E', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('StartTime', models.TimeField(blank=True, null=True)),
                ('EndTime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shopper',
            name='AvailableSlots',
            field=models.ManyToManyField(blank=True, default=1, to='ShopperBase.Slot'),
        ),
    ]
