# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'ShopperBase', '0004_documents'), (b'ShopperBase', '0005_auto_20170615_0222')]

    dependencies = [
        ('ShopperBase', '0003_auto_20170613_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopperPhoneNo', models.BigIntegerField(unique=True)),
                ('AadharImage', models.TextField(blank=True, null=True)),
                ('LicenseImage', models.TextField(blank=True, null=True)),
                ('VehicleRCImage', models.TextField(blank=True, null=True)),
                ('AadharURL', models.CharField(blank=True, max_length=500, null=True)),
                ('LicenseURL', models.CharField(blank=True, max_length=500, null=True)),
                ('VehicleRCURL', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
