# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperBase', '0005_auto_20170624_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='IsOnline',
            field=models.BooleanField(default=True),
        ),
    ]
