# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperBase', '0007_auto_20170706_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopperPhoneNo', models.BigIntegerField(unique=True)),
                ('DisplayPicture', models.TextField(blank=True, null=True)),
                ('DisplayPictureURL', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopper',
            name='IdType',
            field=models.CharField(blank=True, default=b'Aadhar Card', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='Vehicle',
            field=models.CharField(blank=True, default=b'Car', max_length=50),
        ),
    ]
