# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperBase', '0008_auto_20170709_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopperimage',
            name='DisplayPictureURL',
        ),
        migrations.AddField(
            model_name='shopper',
            name='DisplayPictureURL',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
