# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'Carts', '0001_initial'), (b'Carts', '0002_cartitem_cartno'), (b'Carts', '0003_auto_20170525_2101'), (b'Carts', '0004_auto_20170525_2107'), (b'Carts', '0005_auto_20170525_2127'), (b'Carts', '0006_auto_20170525_2209'), (b'Carts', '0007_auto_20170527_1618'), (b'Carts', '0008_auto_20170527_1632')]

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('UserBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.FloatField(blank=True, default=0.0)),
                ('DeliveryCharges', models.FloatField(blank=True, default=0.0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
                ('Username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserBase.User')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField(blank=True, default=1.0)),
                ('SubTotal', models.FloatField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
                ('Cart', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='Carts.Cart')),
            ],
        ),
    ]
