# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='CartNo',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
