# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='UserPhone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
