# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_cartitem_cartno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Cart',
            new_name='Carti',
        ),
    ]
