# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_cart_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='UserPhone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
