# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0003_auto_20170525_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Carti',
            new_name='Cart',
        ),
    ]
