# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0005_auto_20170617_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ProId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
