# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0005_auto_20170525_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='CartNo',
        ),
        migrations.AddField(
            model_name='cart',
            name='AllItems',
            field=models.ManyToManyField(blank=True, to='Carts.CartItem'),
        ),
    ]
