# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0006_auto_20170525_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='AllItems',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Cart',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='Carts.Cart'),
        ),
    ]
