# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0006_cartitem_proid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='IsOrdered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='OrderId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='RemovedFromCart',
            field=models.BooleanField(default=False),
        ),
    ]
