# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0007_auto_20170624_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Product'),
        ),
    ]
