# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0008_auto_20170624_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='OrderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='OrderBase.Order'),
        ),
    ]
