# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ItemsList', '0001_initial'),
        ('BatchBase', '0001_initial'),
        ('ShopperBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField(unique=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('DeliveryCharge', models.FloatField(blank=True, default=0.0, null=True)),
                ('PlacingTime', models.DateTimeField(auto_now_add=True)),
                ('DeliveryAddress', models.CharField(max_length=300, null=True)),
                ('Earnings', models.FloatField(blank=True, default=0.0, null=True)),
                ('UserRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('ShopperRating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('IsDelivered', models.BooleanField(default=False)),
                ('DeliveryDate', models.DateField(blank=True, null=True)),
                ('StartTime', models.TimeField(blank=True, null=True)),
                ('EndTime', models.TimeField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('PriorityScore', models.IntegerField(blank=True, null=True)),
                ('BatchId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BatchBase.Batches')),
                ('Items', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ItemsList.ItemList')),
                ('ShopperId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopperBase.Shopper')),
            ],
        ),
    ]
