# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='Shopper',
        ),
        migrations.AlterField(
            model_name='order',
            name='BatchId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BatchBase.Batches'),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
