# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0002_auto_20170116_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
