# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0010_auto_20170613_1746'),
        ('OrderBase', '0003_remove_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='OrderId',
        ),
        migrations.AddField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserBase.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='CustomerPhoneNo',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ShopperPhoneNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='BatchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BatchBase.Batches'),
        ),
        migrations.AlterField(
            model_name='order',
            name='DeliveryAddress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='PriorityScore',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ShopperRating',
            field=models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='UserRating',
            field=models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3.0),
        ),
    ]
