# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0004_auto_20170617_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='DeliveryCharge',
            new_name='DeliveryCharges',
        ),
    ]
