# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0005_auto_20170618_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ShopperId',
        ),
    ]
