# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0006_auto_20170618_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='BatchId',
        ),
    ]
