# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0007_remove_order_batchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
