# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserBase', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField(blank=True, default=1.0)),
                ('SubTotal', models.FloatField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.FloatField(blank=True, default=0.0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserBase.User')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemsList.ItemList'),
        ),
        migrations.AddField(
            model_name='item',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product'),
        ),
    ]
