# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0003_remove_order_items'),
        ('Products', '0001_initial'),
        ('ItemsList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField(blank=True, default=1.0)),
                ('SubTotal', models.FloatField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
                ('OList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='OrderBase.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
    ]
