# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsList', '0002_auto_20170617_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Product'),
        ),
    ]
