# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(blank=True, max_length=200, null=True)),
                ('StoreAddress', models.CharField(blank=True, max_length=300, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('OpeningTime', models.TimeField(blank=True, null=True)),
                ('ClosingTime', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
