# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ContactNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='FirstName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='LastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
