# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBase', '0002_auto_20170613_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='ContactNo',
            new_name='Dealer_ContactNo',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='FirstName',
            new_name='Dealer_FirstName',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='LastName',
            new_name='Dealer_LastName',
        ),
        migrations.AddField(
            model_name='store',
            name='Dealer_EmailId',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Dealer_password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
