# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBase', '0003_auto_20170613_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
