# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_storeid'),
        ('StoreBase', '0004_auto_20170624_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ProductsAvailable',
            field=models.ManyToManyField(blank=True, null=True, to='Products.Product'),
        ),
    ]
