# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBase', '0005_store_productsavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='ProductsAvailable',
            field=models.ManyToManyField(blank=True, to='Products.Product'),
        ),
    ]
