# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBase', '0008_auto_20170709_0350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreTimings',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ProductsAvailable',
        ),
        migrations.AddField(
            model_name='store',
            name='FridayClosingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='FridayOpeningTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='MondayClosingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='MondayOpeningTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='SaturdayClosingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='SaturdayOpeningTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='SundayClosingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='SundayOpeningTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='ThursdayClosingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='ThursdayOpeningTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='TuesdayClosingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='TuesdayOpeningTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='WednesdayClosingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='WednesdayOpeningTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
