# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StoreBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=250)),
                ('Price', models.FloatField(blank=True, default=9.99)),
                ('Category', models.CharField(blank=True, choices=[(b'Footwear', b'Footwear'), (b'Dairy Products', b'Dairy Products'), (b'No specific category', b'No Specific Category')], default=b'No Specific Category', max_length=200, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to=b'productimg/')),
                ('Features', models.TextField(blank=True, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('StoreId', models.ManyToManyField(blank=True, to='StoreBase.Store')),
            ],
        ),
    ]
