# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20170423_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[(b'Footwear', b'Footwear'), (b'Dairy Products', b'Dairy Products'), (b'Furniture', b'Furniture'), (b'Food', b'Food'), (b'No specific category', b'No Specific Category')], default=b'No Specific Category', max_length=200, null=True),
        ),
    ]
