# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_storeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductSize',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
