# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField(blank=True, null=True, unique=True)),
                ('ProductString', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, default=b'No Specific Category', max_length=200, null=True),
        ),
    ]
